### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by nbstrong** [rhiroshi/sunflower-farmers-bot#6]
I am currently working on calculating profit vs gas cost to set the gas limit.

**Comment by nbstrong** [comment]
This could then be extended to choosing the desired fruit / farm level programatically.

**Comment by nbstrong** [comment]
Then we can combine createFarm and Harvest scripts. If the farm doesn't exist, create it, if the farm isn't at the required level for the optimal fruit, level it up, etc, etc.

Planting and harvesting should be separated (aka, no initial state setup by the createFarm script should be needed).

**Comment by rhiroshi** [comment]
i agree that the code should be merged into one file only. Will work on it

**Comment by rhiroshi** [comment]
Done!
